### ISSUE TITLE
Using CrateDBVectorSearch leads to RuntimeError: Collection can't be accessed without specifying dimension size of embedding vectors

### ISSUE THREAD

**Issue by ckurze** [crate-workbench/langchain#6]
```python
from langchain.llms import AzureOpenAI
from langchain.chains import RetrievalQA
from langchain.vectorstores import CrateDBVectorSearch
from langchain.embeddings import OpenAIEmbeddings

embedding = OpenAIEmbeddings(deployment="embedding-gen", 
                chunk_size=1)

Connection_string = "crate://crate@localhost/?schema=langchain"
collection_name = "legal"

vectorstore = CrateDBVectorSearch(
                collection_name=collection_name,
                connection_string=Connection_string,
                embedding_function=embedding
            )

retriever = vectorstore.as_retriever()

from langchain.chat_models import ChatOpenAI
model = ChatOpenAI(model_name="gpt-3.5-turbo")

qa = RetrievalQA.from_chain_type(llm=model, chain_type="stuff", retriever=retriever)

print("init done ...")

while True:
    user_input = input("Enter your input: ")
    output = qa.run(user_input)
    print("Result:", output)
```

Leads to
```
init done ...
Enter your input: what is a weather forecast
Traceback (most recent call last):
  File "/Users/ckurze/development/demos/debugging/chatbot.py", line 59, in <module>
    output = qa.run(user_input)
             ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/chains/base.py", line 505, in run
    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/chains/base.py", line 310, in __call__
    raise e
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/chains/base.py", line 304, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py", line 136, in _call
    docs = self._get_docs(question, run_manager=_run_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py", line 216, in _get_docs
    return self.retriever.get_relevant_documents(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/schema/retriever.py", line 211, in get_relevant_documents
    raise e
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/schema/retriever.py", line 204, in get_relevant_documents
    result = self._get_relevant_documents(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/schema/vectorstore.py", line 585, in _get_relevant_documents
    docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/vectorstores/pgvector.py", line 336, in similarity_search
    return self.similarity_search_by_vector(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/vectorstores/pgvector.py", line 471, in similarity_search_by_vector
    docs_and_scores = self.similarity_search_with_score_by_vector(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/vectorstores/pgvector.py", line 384, in similarity_search_with_score_by_vector
    results = self._query_collection(embedding=embedding, k=k, filter=filter)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/vectorstores/cratedb/base.py", line 227, in _query_collection
    collection = self.get_collection(session)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/vectorstores/cratedb/base.py", line 122, in get_collection
    raise RuntimeError(
RuntimeError: Collection can't be accessed without specifying dimension size of embedding vectors

```

**Comment by amotl** [comment]
Hi Christian,

thank you for providing a reproducible example program. I was able to confirm the error. I think it is clearly a flaw, because the SQLAlchemy model classes will only be created dynamically by `model_factory`, and this is currently only happening in `add_embeddings()`.

When "just retrieving data", `add_embeddings()` will probably never be called, naturally. So, we will need to find a different approach here.

With kind regard,
Andreas.

**Comment by amotl** [comment]
GH-7 resolves this issue. Thanks again for reporting.

/cc @hammerhead

**Comment by ckurze** [comment]
Thanks for this fast fix!
